/*
 * Copyright (c) 2017-2023 zhllxt
 *
 * author   : zhllxt
 * email    : 37792738@qq.com
 * 
 * Distributed under the Boost Software License, Version 1.0. (See accompanying
 * file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */

#pragma once

#include <asio3/config.hpp>

#if !defined(ASIO3_HEADER_ONLY) && __has_include(<boost/predef.h>)
#include <boost/predef.h>

#ifndef ASIO3_OS_IOS
#define ASIO3_OS_IOS   BOOST_OS_IOS
#endif
#ifndef ASIO3_OS_LINUX
#define ASIO3_OS_LINUX BOOST_OS_LINUX
#endif
#ifndef ASIO3_OS_MACOS
#define ASIO3_OS_MACOS BOOST_OS_MACOS
#endif
#ifndef ASIO3_OS_UNIX
#define ASIO3_OS_UNIX  BOOST_OS_UNIX
#endif
#ifndef ASIO3_OS_WINDOWS
#define ASIO3_OS_WINDOWS BOOST_OS_WINDOWS
#endif
#ifndef ASIO3_OS_SOLARIS
#define ASIO3_OS_SOLARIS BOOST_OS_SOLARIS
#endif
#ifndef ASIO3_OS_BSD_FREE
#define ASIO3_OS_BSD_FREE BOOST_OS_BSD_FREE
#endif
#ifndef ASIO3_OS_BSD_NET
#define ASIO3_OS_BSD_NET BOOST_OS_BSD_NET
#endif
#ifndef ASIO3_OS_BSD_DRAGONFLY
#define ASIO3_OS_BSD_DRAGONFLY BOOST_OS_BSD_DRAGONFLY
#endif
#ifndef ASIO3_OS_QNX
#define ASIO3_OS_QNX BOOST_OS_QNX
#endif

#ifndef ASIO3_ENDIAN_BIG_BYTE
#define ASIO3_ENDIAN_BIG_BYTE BOOST_ENDIAN_BIG_BYTE
#endif
#ifndef ASIO3_ENDIAN_BIG_WORD
#define ASIO3_ENDIAN_BIG_WORD BOOST_ENDIAN_BIG_WORD
#endif
#ifndef ASIO3_ENDIAN_LITTLE_BYTE
#define ASIO3_ENDIAN_LITTLE_BYTE BOOST_ENDIAN_LITTLE_BYTE
#endif
#ifndef ASIO3_ENDIAN_LITTLE_WORD
#define ASIO3_ENDIAN_LITTLE_WORD BOOST_ENDIAN_LITTLE_WORD
#endif

#ifndef ASIO3_ARCH_WORD_BITS_64
#define ASIO3_ARCH_WORD_BITS_64 BOOST_ARCH_WORD_BITS_64
#endif
#ifndef ASIO3_ARCH_WORD_BITS_32
#define ASIO3_ARCH_WORD_BITS_32 BOOST_ARCH_WORD_BITS_32
#endif
#ifndef ASIO3_ARCH_WORD_BITS_16
#define ASIO3_ARCH_WORD_BITS_16 BOOST_ARCH_WORD_BITS_16
#endif
#ifndef ASIO3_ARCH_WORD_BITS
#define ASIO3_ARCH_WORD_BITS BOOST_ARCH_WORD_BITS
#endif

#else
#include <asio3/bho/predef.h>

#ifndef ASIO3_OS_IOS
#define ASIO3_OS_IOS   BHO_OS_IOS
#endif
#ifndef ASIO3_OS_LINUX
#define ASIO3_OS_LINUX BHO_OS_LINUX
#endif
#ifndef ASIO3_OS_MACOS
#define ASIO3_OS_MACOS BHO_OS_MACOS
#endif
#ifndef ASIO3_OS_UNIX
#define ASIO3_OS_UNIX  BHO_OS_UNIX
#endif
#ifndef ASIO3_OS_WINDOWS
#define ASIO3_OS_WINDOWS BHO_OS_WINDOWS
#endif
#ifndef ASIO3_OS_SOLARIS
#define ASIO3_OS_SOLARIS BHO_OS_SOLARIS
#endif
#ifndef ASIO3_OS_BSD_FREE
#define ASIO3_OS_BSD_FREE BHO_OS_BSD_FREE
#endif
#ifndef ASIO3_OS_BSD_NET
#define ASIO3_OS_BSD_NET BHO_OS_BSD_NET
#endif
#ifndef ASIO3_OS_BSD_DRAGONFLY
#define ASIO3_OS_BSD_DRAGONFLY BHO_OS_BSD_DRAGONFLY
#endif
#ifndef ASIO3_OS_QNX
#define ASIO3_OS_QNX BHO_OS_QNX
#endif

#ifndef ASIO3_ENDIAN_BIG_BYTE
#define ASIO3_ENDIAN_BIG_BYTE BHO_ENDIAN_BIG_BYTE
#endif
#ifndef ASIO3_ENDIAN_BIG_WORD
#define ASIO3_ENDIAN_BIG_WORD BHO_ENDIAN_BIG_WORD
#endif
#ifndef ASIO3_ENDIAN_LITTLE_BYTE
#define ASIO3_ENDIAN_LITTLE_BYTE BHO_ENDIAN_LITTLE_BYTE
#endif
#ifndef ASIO3_ENDIAN_LITTLE_WORD
#define ASIO3_ENDIAN_LITTLE_WORD BHO_ENDIAN_LITTLE_WORD
#endif

#ifndef ASIO3_ARCH_WORD_BITS_64
#define ASIO3_ARCH_WORD_BITS_64 BHO_ARCH_WORD_BITS_64
#endif
#ifndef ASIO3_ARCH_WORD_BITS_32
#define ASIO3_ARCH_WORD_BITS_32 BHO_ARCH_WORD_BITS_32
#endif
#ifndef ASIO3_ARCH_WORD_BITS_16
#define ASIO3_ARCH_WORD_BITS_16 BHO_ARCH_WORD_BITS_16
#endif
#ifndef ASIO3_ARCH_WORD_BITS
#define ASIO3_ARCH_WORD_BITS BHO_ARCH_WORD_BITS
#endif

#endif
